[project]
name = "jupyter-cleaner"
version = "0.1.0"
description = "Convert Jupyter notebooks to clean, compact Markdown."
readme = "README.md"
authors = [
    { name = "Danielle Nova", email = "99331448+oNovalSliveDNo@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "typer",
]

[project.scripts]
jupyter-cleaner = "jupyter_cleaner.cli:app"

[build-system]
requires = ["uv_build>=0.7.22,<0.8.0"]
build-backend = "uv_build"

[tool.mypy]
python_version = "3.13"
strict = true

[dependency-groups]
dev = [
    "mypy>=2.3.1",
]
